name: Test

on:
  [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm 
        key: ${{ runner.OS }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

    # avoid "System limit for number of file watchers reached" error
    - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - run: npm ci
    - run: npm run lint
    - run: npm run build
